optkon/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings
from rest_framework import routers
from catalog.views import ProductViewSet
from order.views import OrderViewSet
from .views import IndexView

router = routers.DefaultRouter()
router.register(r'product', ProductViewSet)
router.register(r'order', OrderViewSet)

urlpatterns = [
    path('',IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('api/',include(router.urls))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/models.py
from django.db import models
from easy_thumbnails.fields import ThumbnailerImageField


class Category(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название категории")    

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

class Product(models.Model):
    name = models.CharField(max_length=255, verbose_name="Название")
    category = models.ForeignKey(Category,on_delete=models.DO_NOTHING,null=True, blank=True, verbose_name="Категория")
    description = models.TextField(verbose_name="Описание")
    img = ThumbnailerImageField(upload_to='img/', verbose_name='фото', blank=True, null=True)
    available = models.BooleanField(default=True,blank=True, verbose_name="Доступно на сайте")
    weight = models.FloatField(blank=True, null=True, verbose_name="Вес")

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукт"

class Photos(models.Model):    
    product = models.ForeignKey(Product,blank=True,null=True, on_delete = models.DO_NOTHING, related_name='photo_gallery_set')
    img = ThumbnailerImageField(upload_to='img/')

    class Meta:
        verbose_name=u'Фото'
        verbose_name_plural=u'Фото'

order/models.py
from django.db import models
from catalog.models import Product
# from django.contrib.sessions.models import Session

# Create your models here.

class Order(models.Model):
    # session = models.ForeignKey(Session,blank=True,null=True,on_delete=models.SET_NULL)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now_add=True,null=True)
    STATUS_CHOICE = (
    ('N','Новый'),
    ('A','Подтвержден'),
    ('S','Оплачен'),
    ('D','Отменен'),
    )
    status = models.CharField(choices=STATUS_CHOICE,max_length=2,default="N")
    

class OrderItem(models.Model):
    order = models.ForeignKey(Order,on_delete=models.PROTECT)
    product = models.ForeignKey(Product,blank=True,null=True,on_delete=models.CASCADE)
    count = models.IntegerField()

catalog/views.py
from rest_framework import viewsets
from django_filters import FilterSet
from catalog.models import Product
from django_filters.rest_framework import DjangoFilterBackend
from . serializers import ProductSerializer
from django.shortcuts import render

def index(request):
    return render(request,'index.html',{} )


class LodgeSetFilter(FilterSet):
    class Meta:
        model = Product
        fields = ['name', 'available']

class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    model = Product
    serializer_class = ProductSerializer
    filter_backends = [DjangoFilterBackend,]
    filterset_class  = LodgeSetFilter

optkon/views.py
from django.views.generic import TemplateView

class IndexView(TemplateView):
    template_name=  "index.html"

order/views.py
from rest_framework import viewsets
from django_filters import FilterSet
from order.models import Order
from django_filters.rest_framework import DjangoFilterBackend
from . serializers import OrderSerializer


class OrderViewSet(viewsets.ModelViewSet):
    queryset = Order.objects.all()
    model = Order
    serializer_class = OrderSerializer
    filter_backends = [DjangoFilterBackend,]

catalog/templates/index.html
<!DOCTYPE html>
<html lang="ru">

<head>
  <link rel="preconnect" href="https://fonts.gstatic.com/" crossorigin="anonymous">
  <link rel="preload" as="style" onload="this.rel='stylesheet'" href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap">
  <link rel="preload" as="font" type="font/eot" href="/static/materialdesignicons-webfont-861aea05.eot" crossorigin="anonymous">
  <link rel="preload" as="font" type="font/woff2" href="/static/materialdesignicons-webfont-e52d60f6.woff2" crossorigin="anonymous">
  <link rel="preload" as="font" type="font/woff" href="/static/materialdesignicons-webfont-48d3eec6.woff" crossorigin="anonymous">
  <link rel="preload" as="font" type="font/ttf" href="/static/materialdesignicons-webfont-bd725a7a.ttf" crossorigin="anonymous">

  <meta charset="UTF-8" />
  <link rel="icon" href="/favicon.ico" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>ОптКон</title>
  <script type="module" crossorigin src="/static/index-57055739.js"></script>
  <link rel="stylesheet" href="/static/index-5dff9a37.css">
</head>

<body>
  <div id="app"></div>
  
</body>

</html>

order/templates/order_mail.html
<style>
    table td, .table th {
      padding: .75rem;
      vertical-align: top;
      border-top: 1px solid #dee2e6;
    }    
    </style>
    
    <h1>  
        {% if order.status == 'N' %}
        Новый
        {%else%}
        Изменен
        {%endif%}
        заказ {{order.id}}</h1>
    
    <div> <b>ФИО</b>: {{order.name}}</div>
    <div><b>email</b>: {{order.email}}</div>
    <div> <b>телефон</b>: {{order.phone}}</div>
    <hr>     
    <table>
        <thead>
            <tr>
                <!-- <th>id</th> -->
                <th>Название</th>
                <!-- <th>цена</th> -->
                <th>Количество </th>
                <!-- <th>Итого</th> -->
            </tr>
        </thead>
        <tbody>
            {%for item in order.orderitem_set.all %}
            <tr>
                <!-- <td>{{item.goods.id}}</td> -->
                <td>{{item.product.name}}</td>
                <!-- <td>{{item.price}}</td> -->
                <td align="center">{{item.count}}</td>
                <!-- <td>{{item.total_cost}}</td> -->
             </tr>
             {%endfor%}
            <!-- <tr>
                <td><b>Итого</b></td>
                <td></td>
                <td></td>
                <td></td>
                <td>{{order.total_cost}}</td>
             </tr> -->
     
        </tbody>
    </table>
    